name: ci

on:
  push:
  pull_request:

jobs:
  moonbit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1.22
      - run: moon version --all
      - run: moon fmt --check
      - run: moon check
      - run: moon build
      - run: moon test
      - run: moon package --list
